### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#1]
First order of business is figuring out what data we'll be using. There is a decent sized collection of actuarial datasets in [CASdatasets](http://dutangc.free.fr/pub/RRepos/web/CASdatasets-index.html) (unaffiliated with the Casualty Actuarial Society, name seems to be a concidence...). E.g.

```
library(tidyverse)
library(CASdatasets)
data("freMPL1")
glimpse(freMPL1)
# Observations: 30,595
# Variables: 22
# $ Exposure    <dbl> 0.583, 0.200, 0.083, 0.375, 0.500, 0.499, 0.2...
# $ LicAge      <int> 366, 187, 169, 170, 224, 230, 169, 232, 241, ...
# $ RecordBeg   <date> 2004-06-01, 2004-10-19, 2004-07-16, 2004-08-...
# $ RecordEnd   <date> NA, NA, 2004-08-16, NA, 2004-07-01, NA, 2004...
# $ VehAge      <fct> 2, 0, 1, 1, 3, 3, 6-7, 4, 5, 2, 2, 6-7, 2, 3,...
# $ Gender      <fct> Female, Male, Female, Female, Male, Male, Mal...
# $ MariStat    <fct> Other, Alone, Other, Other, Other, Other, Oth...
# $ SocioCateg  <fct> CSP1, CSP55, CSP1, CSP1, CSP47, CSP47, CSP50,...
# $ VehUsage    <fct> Professional, Private+trip to office, Profess...
# $ DrivAge     <int> 55, 34, 33, 34, 53, 53, 32, 38, 39, 43, 44, 5...
# $ HasKmLimit  <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
# $ BonusMalus  <int> 72, 80, 63, 63, 72, 68, 50, 57, 54, 76, 72, 5...
# $ VehBody     <fct> sedan, microvan, other microvan, other microv...
# $ VehPrice    <fct> D , K , L , L , L , L , G , B , B , M , M , L...
# $ VehEngine   <fct> injection, direct injection overpowered, dire...
# $ VehEnergy   <fct> regular, diesel, diesel, diesel, diesel, dies...
# $ VehMaxSpeed <fct> 160-170 km/h, 170-180 km/h, 170-180 km/h, 170...
# $ VehClass    <fct> B, M1, M1, M1, 0, 0, B, A, A, M2, M2, M1, M1,...
# $ ClaimAmount <dbl> 0.0000, 0.0000, 0.0000, 0.0000, 1418.6103, 0....
# $ RiskVar     <int> 15, 20, 17, 17, 19, 19, 19, 19, 19, 10, 10, 1...
# $ Garage      <fct> None, None, None, Private garage, None, None,...
# $ ClaimInd    <int> 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...
```

@bigalxyz Could you take a look at the data package and see if any datasets would suffice? After installing the package per the instructions at [http://dutangc.free.fr/pub/RRepos/web/CASdatasets-index.html](http://dutangc.free.fr/pub/RRepos/web/CASdatasets-index.html) you can run `?CASdatasets` to see the documentation.

**Comment by TylerGrantSmith** [comment]
@kevinykuo I would like to get involved with this project.  The French Pricing Game datasets would seem to be perfect for these goals, if we had access to the actual test data results.  Maybe @freakonometrics would be able to provide this?  If not, the two Brazillian datasets, `brvehins1` and `brvehins2` would be good candidates.

**Comment by kevinykuo** [comment]
@TylerGrantSmith awesome! This does look really cool https://freakonometrics.hypotheses.org/50078 and I'll spend some time going through it. Thanks for pointing this out. Does your comment imply the labels aren't readily available?

**Comment by genedan** [comment]
Is there a particular LOB that you favor? It seems like we're already leaning towards auto (probably the easiest one to get data for). I think it would be pretty difficult to get something that mirrors the level of complexity (and pain) of what you'd find at a large carrier.

One interesting place to get data is the NHTSA: https://www.nhtsa.gov/research-data. The CRSS and FARS data in particular are very well-documented, have about 200-something variables that, when denormalized, expand to over 5,000 variables. There's an internal Milliman project that I'm getting approval for to be open-sourced (already completed, repo'd, and documented) that may help.

Unfortunately, no dollar amounts or sense of denominator (records are only crashes) are available, so it's not really going to help you from a pricing standpoint, although it would be helpful for certain claims models such as triaging for injury severity and first responder notification. But, given the well-documented nature of the data set, it could give us clues for what we need to look for (or what may be out there).

**Comment by merlinoa** [comment]
@kevinykuo if you are looking for basic P/C triangles across a bunch of different insurers, the `casdata` R package might be useful: https://github.com/Ractuary/casdata

The `casdata` package contains the data from a 2011 CAS loss reserving study: https://www.casact.org/research/index.cfm?fa=loss_reserves_data

**Comment by kevinykuo** [comment]
@genedan Not married to a particular LOB, and I think eventually we'll want to expand to capture the subtleties in each, but for now we should try to get started ASAP.

@TylerGrantSmith I looked at the data and it does seem like only the first year's data is labeled for the French games (and is available in CASdatasets, see `?pricingame`.)

Could y'all take a look at these and opine on which one of these or something else you think you would be best to get started?

**Comment by kevinykuo** [comment]
If no one suggests otherwise I'll begin working on the Brazilian datasets, which seems to have enough variables for a nontrivial analysis.
```
> dplyr::glimpse(brvehins1a)
Observations: 393,071
Variables: 23
$ Gender              <fct> Female, Female, Female, Male, Male, Male, Mal...
$ DrivAge             <fct> >55, 36-45, 18-25, >55, 36-45, 26-35, 18-25, ...
$ VehYear             <int> 1997, 2010, 2008, 2004, 2009, 1998, 1999, 200...
$ VehModel            <fct> Gm - Chevrolet - Kadett Gl 2.0 Mpfi / Efi, Gm...
$ VehGroup            <fct> Gm Chevrolet Kadett, Gm Chevrolet Montana, Vw...
$ Area                <fct> Interior, Maranhao, Mato Grosso do Sul, Met. ...
$ State               <fct> Rio de Janeiro, Maranhao, Mato Grosso do Sul,...
$ StateAb             <fct> RJ, MA, MS, RS, SP, RS, SP, SP, MG, RS, MA, R...
$ ExposTotal          <dbl> 1.01, 3.00, 1.01, 1.45, 4.55, 1.00, 1.01, 1.5...
$ ExposFireRob        <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
$ PremTotal           <dbl> 742.75, 5025.68, 916.26, 1601.68, 53031.35, 6...
$ PremFireRob         <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
$ SumInsAvg           <dbl> 10852.99, 31009.73, 24977.18, 35932.66, 30188...
$ ClaimNbRob          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
$ ClaimNbPartColl     <dbl> 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, ...
$ ClaimNbTotColl      <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
$ ClaimNbFire         <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
$ ClaimNbOther        <dbl> 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, ...
$ ClaimAmountRob      <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
$ ClaimAmountPartColl <dbl> 0, 0, 0, 0, 648, 2773, 0, 0, 0, 0, 1512, 0, 0...
$ ClaimAmountTotColl  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
$ ClaimAmountFire     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
$ ClaimAmountOther    <dbl> 0, 0, 0, 0, 0, 120, 0, 0, 0, 0, 320, 0, 0, 0,...
```

Also, we can validate on "future" years since there seems to be more data here http://www2.susep.gov.br/menuestatistica/Autoseg/principal.aspx (although my Portuguese isn't great.)

One thing this is missing is past claims history, but from my googling I didn't see any dataset with that info.

**Comment by kevinykuo** [comment]
@bigalxyz @genedan @TylerGrantSmith would be great to get a thumbs up/down from you before we go all-in viva la brasil this

**Comment by TylerGrantSmith** [comment]
:+1:  , aside  from the fact that it seems I cannot access the site.  `www2.susep.gov.br’s server IP address could not be found`.  I will check again later today.
