### ISSUE TITLE
read_raw_data() doesn't map peril names

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#117]
The logic was lost when transitioning to drake...

**Comment by actuarialvoodoo** [comment]
Can you clarify the problem here? 
When I pulled in the master branch and I could run all targets without errors. 
I also ran the read_raw_data manually and I see the peril codes imported

![image](https://user-images.githubusercontent.com/11914172/67164368-b9fb6a00-f347-11e9-8c36-7dbea5b38859.png)

**Comment by kevinykuo** [comment]
The mapping was done via a `rename()` because they are column names. This is kinda failing "silently" right now and the claim amounts are all 0 ;)
