### ISSUE TITLE
Outline of tasks in pricing

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#2]
While we're deciding on the data, we can put together an outline of typical things that need to be done, i.e. specific tasks in data prep, modeling, preparing reports. I expect this to evolve over time but we need something to get going.

Who would like to give a shot at this?

**Comment by genedan** [comment]
I could help with everything up to filing (basically from project inception to sign off on loss costs). I have no experience with filing.

Are we going to touch implementation at all (coding stuff up in something like Guidewire)?

Where should we put the outline? Put a Markdown file in the repo? In the Wiki?

**Comment by kevinykuo** [comment]
I think we should do the end-to-end, so yeah let's talk about model monitoring and considerations for the next model update. As much as possible we should offer a way to do everything via open source technologies while talking about conventional/popular ways of doing things, e.g. "you typically recode the GLM on [proprietary tech], but you can also deploy it using MLflow or something, and here's an example with code."

For the outline, an .md in the root should be fine for now.

**Comment by kevinykuo** [comment]
This might be useful: https://www.casact.org/research/wp/papers/working-paper-spedicato-%202012-06.pdf

**Comment by kevinykuo** [comment]
@genedan Still working on this? For now we just need the immediate next steps (probably related to EDA, but you'll know better.)

**Comment by genedan** [comment]
hey @kevinykuo , I should be able to get something out tonight. For now it'll just be a straight up list of bullet points but that'll get the ball rolling. We can categorize and refine as we move along. Bill targets are aggressive this month, but I'll help when I can.

**Comment by kevinykuo** [comment]
Marking this closed since we mostly have a path forward.
