### ISSUE TITLE
Figure out what EXPOSICAO2 and PREMIO2 are

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#52]

**Comment by rafaelcosta1** [comment]
These are apparently defined as "field not utilized". Someone sent a question to Brazil's "Access to Information" website (which I did not know existed), and SUSEP responded with a definition of multiple fields, including those two: http://www.consultaesic.cgu.gov.br/busca/dados/Lists/Pedido/Item/displayifs.aspx?List=0c839f31-47d7-4485-ab65-ab0cee9cf8fe&ID=526869&Web=88cc5f44-8cfe-4964-8ff4-376b5ebb3bef

**Comment by kevinykuo** [comment]
@rafaelcosta1 That is super cool! If only the US gov't agencies were that awesome...

Really appreciate your being here and welcome to GitHub! If you uncover subtleties in the data that are relevant please feel free to comment on/open issues/send PRs.
