### ISSUE TITLE
automate analysis plan

### ISSUE THREAD

**Issue by actuarialvoodoo** [kasaai/pc-pricing-tutorial#74]
We want to specific the execution plan for the analysis so that it can be automated. Concern that GNU make might be too complicated for new users. Want to investigate usage of drake.

**Comment by actuarialvoodoo** [comment]
I came across this [repo](https://github.com/jdblischak/r-project-workflows#readme) which is a task view proposal for project workflows. Could be useful for kasa ai projects.

**Comment by kevinykuo** [comment]
Started porting the workflow to use drake.
